# Generated by Django 5.0.1 on 2024-02-12 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvmaze_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('genres', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True)),
                ('premiered', models.DateField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchListShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_status', models.CharField(choices=[('WATCHED', 'Watched'), ('CURRENTLY_WATCHING', 'Currently Watching'), ('TO_WATCH', 'To Watch')], max_length=20)),
                ('favourite', models.BooleanField(default=False)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='watchlist.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shows', models.ManyToManyField(to='watchlist.watchlistshow')),
            ],
        ),
    ]
